name: Build Wheels

on:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-package:
    name: Build
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install python dependencies
      run: pip install build twine

    - name: Build sdist and wheel
      run: |
        python -m build

    - name: List and check
      run: |
        ls -lh dist/
        twine check dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./dist/*
        # name: wheels
